name: fan_easy
description: "FanEasy is a simple Flutter package for seamless integration of Facebook Audience Network ads with easy-to-use methods."
homepage: https://github.com/matifdeveloper/fan_easy
repository: https://github.com/matifdeveloper/fan_easy
version: 0.0.1
fan_easy:
  path: ../fan_easy

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  facebook_audience_network: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
